N = 2^16
itemp = 0
irand = zeros(N,1);

% Generate random numbers with the 16 bit linear congruential generator:
if(1)
for i = 1:N
   irand(i) = itemp;
   itemp = mod(53*itemp + 15473, N);
end
else
  irand = fix(N*rand(N,1));
end

% Interpret irand as 16 bit twos-complement binary numbers:
ineg = find(irand >= N/2);
irand(ineg) = irand(ineg) - N;  

% Right shift the twos-complement numbers to divide by 2:
% (This gives the actual sequence of numbers generated by the
% noise generator in the Versa-Filter V2.00 code)
irand = floor(irand/2);

index_of_zeros = find(irand == 0)   % verify maximum length sequence

% figure, plot(irand), zoom on      % plot noise
figure, hist(irand,128), zoom on    % plot 128 bin histogram


[x, lags] = xcorr(irand, irand);
figure, plot(lags,x)

