% This MATLAB script designs a User FIR filter
% for the Versa-Filter System. It designs an FIR differentiator
% and generates a text output file of coefficients for
% downloading into the Versa-Filter.
%
% A simple way to download the text to the Versa-Filter system
% is to use HyperTerminal. Use the Transfer, Send Text File
% menu option to send the file generated by this program.
%
% The Signal Processing Toolbox must be installed.
%

outfile = 'c:\temp\userfir.txt';    % Modify this path for desired directory name

fs = 48000;     % sampling rate

% Design a differentiator filter:
n_diff = 20;        % even
%diff_coefs = firls(n_diff-1,[0 .95], [0 .95],'differentiator');
diff_coefs = remez(n_diff-1, [0 1], [0 1],'differentiator');

% Plot filter design results:
figure, plot(diff_coefs), title('Impulse response of Differentiator'),zoom on
[h,f] = freqz(diff_coefs,1,1024,fs);
figure, plot(f,abs(h)), grid on, zoom on

% Open and write filter coefs to file:
[fid, measage] = fopen(outfile,'wt');

% Write file that loads Common section of Versa-Filter with differentiator:
fprintf(fid, 'at all Mode:A&B Common\n');
fprintf(fid, 'at all FUNC:UserFIR:');
fprintf(fid, ' %d', round(32768*diff_coefs));   % write coefs
fprintf(fid, '\n');     % write final carriage return


fclose(fid);            % close file
